os: osx
language: objective-c

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    osx_image: xcode9.3

script:
  - swift test

before_install:
  - brew update
  - brew install libsodium
