os: osx
language: objective-c

matrix:
  include:
    - osx_image: xcode9.2
    - osx_image: xcode9.1
    - osx_image: xcode9

  allow_failures:
    - osx_image: xcode9.3beta

script:
  - swift test

before_install:
  - brew update
  - brew install libsodium
