name: Swift
on: [push]
jobs:
  build:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Libsodium
        run: |
          brew update
          brew install libsodium
      - name: Run Tests
        run: swift test