name: Swift
on: [push]
jobs:
  units:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Libsodium
        run: |
          brew update
          brew install libsodium
      - name: Run Tests
        run: swift test

  vectors-not-stale:
    name: Check Test Vectors Up To Date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for updates
        run: |
          cd Tests/PasetoTests/TestVectors
          rm *
          wget https://raw.githubusercontent.com/paseto-standard/test-vectors/master/v{1..4}.json
          git diff --exit-code
